SDT-730: Enviar notificacion al preregistro de usuario
subsesjal/siiges-services pull request #395
Opened 2024-10-02 22:45 UTC by DylanSan29

2024-10-02 23:10 UTC, Calamateo approved these changes
Nice, se ve bien!

![image](https://github.com/user-attachments/assets/d78605c9-f401-4b14-b630-92eb3f9c4a48)

2024-10-04 16:32 UTC, robertotorres-dev commented on packages/notificaciones/src/useCases/services/send.email.services.js
>  };
quitar el mapeo de aquí

2024-10-04 16:32 UTC, robertotorres-dev commented on packages/notificaciones/src/useCases/helpers/preregistroUsuario.topic.js
> +module.exports = { generateMapPreRegisterUser };
eliminar archivo

2024-10-04 16:32 UTC, robertotorres-dev commented on packages/api-gateway/src/drivers/http/adapters/usuarios/handlers/register.handlers.usuarios.adapters.js
> +}
agregar el parámetro de 'usuario' para poner en el correo el usuario registrado

2024-10-04 16:33 UTC, robertotorres-dev commented on packages/notificaciones/src/useCases/helpers/index.js
> +  generateMapPreRegisterUser,
quitar la función

2024-10-04 16:34 UTC, robertotorres-dev requested changes
atender comentarios

2024-10-04 18:04 UTC, DylanSan29 commented on packages/notificaciones/src/useCases/services/send.email.services.js
>  };
Listo

2024-10-04 18:04 UTC, DylanSan29 commented on packages/notificaciones/src/useCases/helpers/preregistroUsuario.topic.js
> +module.exports = { generateMapPreRegisterUser };
Listo

2024-10-04 18:04 UTC, DylanSan29 commented on packages/api-gateway/src/drivers/http/adapters/usuarios/handlers/register.handlers.usuarios.adapters.js
> +}
Listo

2024-10-04 18:04 UTC, DylanSan29 commented on packages/notificaciones/src/useCases/helpers/index.js
> +  generateMapPreRegisterUser,
Listo

2024-10-08 17:58 UTC, robertotorres-dev approved these changes

2024-10-08 17:59 UTC, merged